# Generated by Django 3.1.1 on 2020-09-05 19:49
from django.db import migrations


def add_group_data(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    db_alias = schema_editor.connection.alias
    group = Group.objects.using(db_alias).create(name="普通用户")
    group.save()
    group.permissions.set(
        Permission.objects.using(db_alias).filter(codename__iendswith="log")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20200904_0211"),
        ("logs", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_group_data),
    ]
