# Generated by Django 3.1.1 on 2020-09-04 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0002_auto_20200904_0137"),
    ]

    operations = [
        migrations.AlterModelOptions(name="dnslog", options={"ordering": ["-id"]},),
        migrations.AlterModelOptions(name="weblog", options={"ordering": ["-id"]},),
    ]
