# Generated by Django 3.1.1 on 2020-09-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20200904_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnslog',
            name='client_ip',
            field=models.TextField(blank=True, help_text='客户端IP', max_length=256),
        ),
    ]
