# Generated by Django 3.1.1 on 2020-09-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_auto_20200905_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblog',
            name='host',
            field=models.CharField(default='', help_text='请求域名', max_length=300),
            preserve_default=False,
        ),
    ]
